# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[('style.qss', '.'), ('icon.ico', '.'), ('icon.png', '.')],
    hiddenimports=[
        'local_engine',
        'model_manager',
        'context_engine',
        'orchestrator',
        'agent_tools',
        'settings',
        'settings_dialog',
        'ui.main_window',
        'ui.components',
        'threads.workers',
        'git_integration',
        'git_dialog',
        'llama_cpp',
        'openai',
        'requests',
        'httpx',
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtNetwork',
        'shiboken6',
        'numpy',
        'jinja2',
        'certifi',
        'cryptography',
        'bcrypt',
        'sqlite3',
        'multiprocessing',
        'pkg_resources.py2_warn',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='AI-Assistant',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)
